name: Android Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v11
      with:
        java-version: 8.0
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Espresso tests
      run: ./gradlew connectedAndroidTest
