name: Testes de unidade

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '12'

    - name: Build com Gradle
      run: ./gradlew build

    - name: Execução dos testes de unidade
      run: ./gradlew test
